### ISSUE TITLE
feedback on "getstarted" vignette?

### ISSUE THREAD

**Issue by aappling-usgs** [USGS-R/streamMetabolizer#175]
@cklunch @robohall @jread-usgs - i've drafted a vignette to introduce new users to `streamMetabolizer`. It's here: http://usgs-r.github.io/streamMetabolizer/getstarted.html. If you have any thoughts or early reactions to this vignette and/or the user interface, I'd love to hear them.
* is the interface intuitive? is there anything i could do to make it even easier to use? could you identify your modeling options, find & meet the data formatting requirements, and choose and run a model?
* is the vignette useful? confusing? exciting? what needs to be explained better or earlier or in a separate vignette?

**Comment by robohall** [comment]
Looks great, I will have lots of questions tomorrow at 8 AM.

Bob
On Mar 23, 2016, at 2:21 PM, Alison Appling <notifications@github.com<mailto:notifications@github.com>> wrote:


@cklunch<https://github.com/cklunch> @robohall<https://github.com/robohall> @jread-usgs<https://github.com/jread-usgs> - i've drafted a vignette to introduce new users to streamMetabolizer. It's here: http://usgs-r.github.io/streamMetabolizer/getstarted.html. If you have any thoughts or early reactions to this vignette and/or the user interface, I'd love to hear them.

  *   is the interface intuitive? is there anything i could do to make it even easier to use? could you identify your modeling options, find & meet the data formatting requirements, and choose and run a model?
  *   is the vignette useful? confusing? exciting? what needs to be explained better or earlier or in a separate vignette?

**Comment by jread-usgs** [comment]
I really like it. Quick feedback for the vignette:
 - provide a quick view of the dataset before all of the `dplyr` and `ggplot2` fanciness? 
 - `metab_inputs('mle', 'data')` should be clear that you are seeing a slice of example data, not *your* data
 - I really like the pattern of `specs` and `replace` shown for altering specifications
 - no units in `preds`? or is that just the way `kable` is dealing with it?

**Comment by aappling-usgs** [comment]
Thanks, Jordan. Quick replies (to be actually addressed later):
* like a `head(dat)`? good idea, i'll add that.
* right. i will clarify.
* great!
* some of both - i make occasional progress on adding units here & there, but they're not yet systemic (e.g., https://github.com/USGS-R/streamMetabolizer/issues/29 is still a live issue). i could add optional units to predict_metab() and predict_DO() without too much headache, though - just added an issue (https://github.com/USGS-R/streamMetabolizer/issues/176).

**Comment by cklunch** [comment]
This is great! I love the customizability, and it's very clear. I agree a quick view of the data at the top would be nice.

The only problem I ran into in going through this was making sure I had the appropriate packages loaded, I ended up having to dig around a bit to figure out what I needed and find them. So expanding the "load libraries" command at the top would be useful. The packages I needed that weren't on the list were unitted, knitr, and runjags (and maybe rjags too? I started out with only rjags loaded and it wouldn't run without runjags, but I couldn't tell if I needed both). But knitr is unimportant, since it only makes the tables here. If you want this to be an introduction for complete beginners, it might be nice to include instructions at the top for getting packages off GitHub with devtools too, since you need that for unitted and streamMetabolizer itself.

Thanks for looping me in on this!

**Comment by aappling-usgs** [comment]
Thanks, Claire - that's an awesome idea to include installation instructions in the vignette. I will do that!

**Comment by aappling-usgs** [comment]
Thanks, All. I've addressed these suggestions in 23e01387b8e80f63630dc601043f89417a4937f6, 7ff181a613c4c098e5585aeba41cd3bcaa412661, 4d504f99246c86c048c3b92326473d79e97734c0, and 70edda8f764029e87a855505a6d4624c5654c990
