### ISSUE TITLE
calc_depth.R

### ISSUE THREAD

**Issue by aappling-usgs** [USGS-R/streamMetabolizer#27]
Need a function that takes discharge (or something fancier, later) and returns an estimate of depth in m.

**Comment by robohall** [comment]
We are working on that.

z=aQ^b
On Apr 24, 2015, at 3:26 PM, Alison Appling <notifications@github.com<mailto:notifications@github.com>> wrote:


Need a function that takes discharge (or something fancier, later) and returns an estimate of depth in m.

**Comment by aappling-usgs** [comment]
You mean with that undergrad, right? Or something even quicker? I'm really just looking for a placeholder function here that will give us a number that's order-of-magnitude correct. We'll write it so that it's easy to plug in your undergrad's numbers as we get them.

**Comment by robohall** [comment]
No nothing quicker and yes with the undergrad. If you want place holder, we could make up a and use b from standard at a station hydraulic geometry.



On Apr 24, 2015, at 7:10 PM, Alison Appling <notifications@github.com<mailto:notifications@github.com>> wrote:


You mean with that undergrad, right? Or something even quicker? I'm really just looking for a placeholder function here that will give us a number that's order-of-magnitude correct. We'll write it so that it's easy to plug in your undergrad's numbers as we get them.

-

**Comment by aappling-usgs** [comment]
That sounds good. What considerations go into making up a? What data would we need on hydraulic geometry, etc. to find b?
