### ISSUE TITLE
Number of rows for different dates

### ISSUE THREAD

**Issue by berdaniera** [USGS-R/streamMetabolizer#336]
When fitting a bayesian model, I got this error:

> In metab_fun(specs = specs, data = data, data_daily = data_daily,  :
>   Modeling failed: dates have differing numbers of rows; observations cannot be combined in matrix

I see in the code that you are looking at a table of the day length data. My UTC datetimes are all equally spaced, and there are 96 obs per day (except for the first and last days in the data set, easy to trim off). I use:
`convert_UTC_to_solartime(date.time=dd$DateTime_UTC, longitude=md$lon[1], time.type="apparent solar")`
to get the solar.time. Most dates get 96 intervals, but 2 get 95 and two get 97, which I assume is an artifact of the calculation and this particular location. For now I am dropping those days.

I can think of two possibilities:
- let `metab` run but automatically drop the dates with less than the mode of observations per day (with a warning that those dates were dropped because of incorrect dimensions)
- modify `convert_UTC_to_solartime` to recognize when this happens (I think in most cases it would only cause the nobs per day to go up or down by one) and do something (like, would metab accept something like "2016-12-21 24:00:06" instead of "2016-12-22 00:00:06"?)

Let me know if you want me to try to implement a solution.

**Comment by aappling-usgs** [comment]
Thanks for submitting this as a GitHub issue, Aaron.

For more abrupt differences in resolution, e.g., from hourly measurements to 15-minute measurements, I've recently added the `required_timestep` argument to `specs`. If you set this to a non-NA value, this will discard days that don't have the numeric timestep you specified, automating the process you described above.

But for your current case (and in general), you should use "mean solar" instead of "apparent solar" for inputs to metab() - that will get you exactly even intervals and exactly 96 obs per day. The "apparent solar" option should be reserved for calculating light.

**Comment by berdaniera** [comment]
Very good, that makes perfect sense. Thank you!
