### ISSUE TITLE
DO.mod in predict_DO for Bayesian model

### ISSUE THREAD

**Issue by Tzu-Yao** [USGS-R/streamMetabolizer#391]
Hi Alison and Bob,

First of all thank you so much for answering my questions in #390. Your insights are really helpful!
Here I'd like to raise another question about DO.mod in `predict_DO`. As I was trying to calculate the metric for goodness of fit using DO.mod and DO.obs, as described in #367, I'm not sure if this DO.mod from `predict_DO` has been corrected by process error already (I want to know what kinds of error the residuals contain). 
Later I followed #222 and produced two plots, as below. The blue dashed line is DO.mod from mcmc results and the brown line is DO.mod calculated by calc_dDOdt. For the observation model ("b_Kb_oi_tr_plrckm.stan"), the two lines match, but for the state-space model ("b_Kb_oipi_tr_plrckm.stan"), they don't. So I was wondering if this difference is caused by the correction of process error in mcmc calculation. In other words, DO.mod in `predict_DO` (brown line) does not account for process error?

![DO_plots_obs-err_DO pred vs DO mod](https://user-images.githubusercontent.com/39259973/84928527-8589aa80-b09c-11ea-93f6-1fdd5d6e5197.png)
The observation error Bayesian model

![DO_plots_state-space_DO pred vs DO mod](https://user-images.githubusercontent.com/39259973/84928565-9c300180-b09c-11ea-8145-c7cc9d3a9568.png)
The state-space Bayesian model
 
Thank you,
Tzu-Yao

**Comment by aappling-usgs** [comment]
Your interpretation of the software behavior is correct - predict_DO returns predictions for DO that are not corrected for process error, which is why the observation-error-only models show better matches between the observations and the output of that function.

I've had open issues for a couple of years to add in process error corrections within predict_DO (#294, #330). Given that I am no longer actively developing the package, they're not likely to be resolved soon. Fortunately, you can already get the process-error-corrected predictions by requesting that they be tracked in Stan (they're called `DO_mod`):
```r
revise(specs, params_out=c(params_out, 'DO_mod'))
```

Then you just need to pull these DO_mod values out of the instantaneous data.frame within the model `fit`.

**Comment by Tzu-Yao** [comment]
Thank you so much Alison!
